apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-ddbo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-ddbo
    app.kubernetes.io/part-of: test-app-ltsq
  name: test-component-ddbo
  namespace: build-e2e-zqbn-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-ddbo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-ddbo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:e5b2e5a4ede27c7f389a458aca6ccade3b24af5db3a2e8c68d54d8d566163781
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
